export { Home } from './Home'
export { About } from './About'
export { Collezione } from './Collezione'
export { Contatti } from './Contatti'
export { AdminLogin } from './AdminLogin'
export { AdminDashboard } from './AdminDashboard'
